
export const MEDIDAS_ANTROPOMETRICAS = [{
    "ordem":0,
    "item":"1.1",
    "nome":"Estatura, corpo ereto",
    "mediaMulher":161.9,
    "mediaHomem":184.1,
    },
    {
    "ordem":1,
    "item":"1.2",
    "nome":"Altura dos Olhos, em Pé, ereto",
    "mediaMulher":150.2,
    "mediaHomem":161.3,
    },
    {
    "ordem":2,
    "item":"1.3",
    "nome":"Altura dos Ombros, em Pé, ereto",
    "mediaMulher":133.9,
    "mediaHomem":144.5,
    },
    {
    "ordem":3,
    "item":"1.4",
    "nome":"Altura do Cotovelo, em Pé, ereto",
    "mediaMulher":103.0,
    "mediaHomem":109.6,
    },
    {
    "ordem":4,
    "item":"1.5",
    "nome":"Altura do centro da Mão, Braço pendido, em Pé",
    "mediaMulher":73.8,
    "mediaHomem":76.7,
    },
    {
    "ordem":5,
    "item":"1.6",
    "nome":"Altura do centro da Mão, Braço erguido, em Pé",
    "mediaMulher":187.0,
    "mediaHomem":205.1,
    },
    {
    "ordem":6,
    "item":"1.7",
    "nome":"Comprimento do Braço, na horizontal, até o centro da Mão",
    "mediaMulher":69.0,
    "mediaHomem":72.2,
    },
    {
    "ordem":7,
    "item":"1.8",
    "nome":"Profundidade do Corpo, na altura do Tórax",
    "mediaMulher":28.5,
    "mediaHomem":27.6,
    },
    {
    "ordem":8,
    "item":"1.9",
    "nome":"Largura dos Ombros, em Pé",
    "mediaMulher":35.5,
    "mediaHomem":39.8,
    },
    {
    "ordem":9,
    "item":"1.10",
    "nome":"Largura dos Quadris, em Pé",
    "mediaMulher":35.8,
    "mediaHomem":34.4,
    },
    {
    "ordem":10,
    "item":"2.1",
    "nome":"Altura da Cabeça, a partir do assento, Tronco ereto",
    "mediaMulher":85.7,
    "mediaHomem":90.7,
    },
    {
    "ordem":11,
    "item":"2.2",
    "nome":"Altura dos Olhos, a partir do assento, Tronco ereto",
    "mediaMulher":73.5,
    "mediaHomem":79.0,
    },
    {
    "ordem":12,
    "item":"2.3",
    "nome":"Altura dos Ombros, a partir do assento, Tronco ereto",
    "mediaMulher":58.5,
    "mediaHomem":61.0,
    },
    {
    "ordem":13,
    "item":"2.4",
    "nome":"Altura do Cotovelo, a partir do assento, Tronco ereto",
    "mediaMulher":23.3,
    "mediaHomem":23.0,
    },
    {
    "ordem":14,
    "item":"2.5",
    "nome":"Altura do Joelho, sentado",
    "mediaMulher":50.2,
    "mediaHomem":53.5,
    },
    {
    "ordem":15,
    "item":"2.6",
    "nome":"Altura Poplítea (Parte inferior da Coxa)",
    "mediaMulher":39.5,
    "mediaHomem":44.2,
    },
    {
    "ordem":16,
    "item":"2.7",
    "nome":"Comprimento do Antebraço, na horizontal, até o centro da Mão",
    "mediaMulher":32.2,
    "mediaHomem":36.2,
    },
    {
    "ordem":17,
    "item":"2.8",
    "nome":"Comprimento Nádega-Poplítea",
    "mediaMulher":48.4,
    "mediaHomem":50.0,
    },
    {
    "ordem":18,
    "item":"2.9",
    "nome":"Comprimento Nádega-Joelho",
    "mediaMulher":58.7,
    "mediaHomem":59.9,
    },
    {
    "ordem":19,
    "item":"2.10",
    "nome":"Comprimento Nádega-Pé, Perna estendida na horizontal",
    "mediaMulher":104.4,
    "mediaHomem":103.5,
    },
    {
    "ordem":20,
    "item":"2.11",
    "nome":"Altura da parte superior das Coxas",
    "mediaMulher":14.4,
    "mediaHomem":13.6,
    },
    {
    "ordem":21,
    "item":"2.12",
    "nome":"Largura entre os Cotovelos",
    "mediaMulher":45.6,
    "mediaHomem":45.1,
    },
    {
    "ordem":23,
    "item":"2.13",
    "nome":"Largura dos Quadris",
    "mediaMulher":38.7,
    "mediaHomem":36.2,
    },
    {
    "ordem":24,
    "item":"3.1",
    "nome":"Comprimento vertical da Cabeça",
    "mediaMulher":21.9,
    "mediaHomem":22.8,
    },
    {
    "ordem":22,
    "item":"3.2",
    "nome":"Largura da Cabeça, de frente",
    "mediaMulher":14.4,
    "mediaHomem":13.6,
    },
    {
    "ordem":23,
    "item":"3.3",
    "nome":"Largura da Cabeça, de perfil",
    "mediaMulher":18.0,
    "mediaHomem":19.3,
    },
    {
    "ordem":24,
    "item":"3.4",
    "nome":"Distância entre os Olhos",
    "mediaMulher":5.7,
    "mediaHomem":6.3,
    },
    {
    "ordem":25,
    "item":"3.5",
    "nome":"Circunferência da Cabeça",
    "mediaMulher":54.0,
    "mediaHomem":57.3,
    },
    {
    "ordem":26,
    "item":"4.1",
    "nome":"Comprimento da Mão",
    "mediaMulher":17.4,
    "mediaHomem":18.6,
    },
    {
    "ordem":27,
    "item":"4.2",
    "nome":"Largura da Mão",
    "mediaMulher":9.2,
    "mediaHomem":10.7,
    },
    {
    "ordem":28,
    "item":"4.3",
    "nome":"Comprimento da palma da Mão",
    "mediaMulher":10.0,
    "mediaHomem":10.9,
    },
    {
    "ordem":29,
    "item":"4.4",
    "nome":"Largura da palma da Mão",
    "mediaMulher":8.0,
    "mediaHomem":8.5,
    },
    {
    "ordem":30,
    "item":"4.5",
    "nome":"Circunferência da Palma",
    "mediaMulher":19.2,
    "mediaHomem":21.0,
    },
    {
    "ordem":31,
    "item":"4.6",
    "nome":"Circunferência do Pulso",
    "mediaMulher":16.0,
    "mediaHomem":17.6,
    },
    {
    "ordem":32,
    "item":"4.7",
    "nome":"Cilindro de pega Máxima (Diâmetro)",
    "mediaMulher":13.0,
    "mediaHomem":13.8,
    },
    {
    "ordem":33,
    "item":"5.1",
    "nome":"Comprimento do Pé",
    "mediaMulher":24.2,
    "mediaHomem":26.0,
    },
    {
    "ordem":34,
    "item":"5.2",
    "nome":"Largura do Pé",
    "mediaMulher":9.7,
    "mediaHomem":10.0,
    },
    {
    "ordem":35,
    "item":"5.3",
    "nome":"Largura do Calanhar",
    "mediaMulher":6.2,
    "mediaHomem":6.6,
    }
]